### ISSUE TITLE
[Forms] Adjust padding and test responsiveness of the add form screen on smaller devices

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#279]

**Comment by ajeurkar** [comment]
@aniri I would like to work on it. Can you assign this to me?

**Comment by ajeurkar** [comment]
Oh! I see... @Botosio has already asked to work on it. 😄

**Comment by Botosio** [comment]
@aniri I'm working on the responsive design for smaller devices.  Having an issue with the collapse icon on the left, because it's just kind of floating over there and it doesn't seem to be in a 12 grid system.  I'm not trying to change the design but wondered if this makes sense???

Where the delete and the collapse icon fits on a line, and you can see all questions collapsed?
![image](https://user-images.githubusercontent.com/44526601/96123459-d4b3e080-0ec0-11eb-9d08-a04c6bb6375c.png)

**Comment by aniri** [comment]
@Botosio It is ok to adjust the design a bit to make it fit the grid system or make sense. It doesn't have to be pixel perfect :smile: So if you find an easy decent way of showing the collapsed questions, it's perfect :D

**Comment by Botosio** [comment]
@aniri about to check this in, here is the image of what it looks like now
![image](https://user-images.githubusercontent.com/44526601/96258303-cd0c3e80-0f89-11eb-89bc-b29120f01dc9.png)

**Comment by Botosio** [comment]
moblie
![image](https://user-images.githubusercontent.com/44526601/96259671-ef06c080-0f8b-11eb-8565-835221a4c035.png)
